### ISSUE TITLE
"X-CSRF-ZOSMF-HEADER" HTTP Header for z/OSMF

### ISSUE THREAD

**Issue by vibhor-bc** [galasa-dev/managers#423]
z/OSMF requires X-CSRF-ZOSMF-HEADER to be passed in all HTTP requests. Seems this header is not passed by default by [ZosmfZosDatasetImpl](https://github.com/galasa-dev/managers/blob/master/galasa-managers-parent/galasa-managers-zos-parent/dev.galasa.zosfile.zosmf.manager/src/main/java/dev/galasa/zosfile/zosmf/manager/internal/ZosmfZosDatasetImpl.java) while using the code samples mentioned for [z/OS File](https://galasa.dev/docs/managers/zos-manager)

`ERROR d.g.z.i.ZosmfRestApiProcessor - Problem with zOSMF request
dev.galasa.zosmf.ZosmfException: Unexpected HTTP status code: 403
	at dev.galasa.zosmf.internal.ZosmfImpl.get(ZosmfImpl.java:113)
	at dev.galasa.zosmf.internal.ZosmfRestApiProcessor.sendRequest(ZosmfRestApiProcessor.java:74)
	at dev.galasa.zosfile.zosmf.manager.internal.ZosmfZosDatasetImpl.exists(ZosmfZosDatasetImpl.java:264)`

Is there a way to explicitly set this header ? or even pass instance of zosmf manager which already provides a way to set headers ?
How can the file manager be used without setting this header when z/OSMF requires it ?

GALASA version : 0.14.0

Thanks,
Vibhor

**Comment by DavidXRoberts** [comment]
Hi Vibhor,
The X_CSRF_ZOSMF_HEADER header is passed in zOSMF Batch, but nowhere else.   I'll look into fixing that ASAP.

**Comment by DavidXRoberts** [comment]
The updated the Managers are in 0.15.0-SNAPSHOT and will be in 0.15.0 when released
