### ISSUE TITLE
ZosLiberty deployApplication is copying file to wrong location

### ISSUE THREAD

**Issue by ChrisAtkinson1** [galasa-dev/managers#988]
code

Global vars

	private final String appDir = "Spring";

	private final String appName = "spring-0.0.1";

```
		// Upload the application to zfs using the Galsasa temporary directory
		String targetUssFile = lpar.getRunTemporaryUNIXPath() + appName + ".war";
		logger.info("TARGET = " + targetUssFile);
		String sourceWarFilePath = appDir + "/" + appName + ".war";
		logger.info("SOURCE = " + sourceWarFilePath);

		// Deploy the application to the Liberty server.xml
		zosLibertyServer = libertyJVMServer.getLibertyServer();
		zosLibertyServer.deployApplication(this.getClass(), sourceWarFilePath, targetUssFile, ApplicationType.WAR,
				"spring-0.0.1",null);
```

where  the app ends up on disc

/u/user/Galasa/X8/spring-0.0.1.war:>ls
spring-0.0.1.war

What it puts in server.xml

    <application id="spring-0.0.1" location="/u/user/Galasa/X8/spring-0.0.1.war" name="spring-0.0.1" type="war"/>

The place on disc is /u/user/Galasa/X8/spring-0.0.1.war/spring-0.0.1.war

So the server will not pick the war up as it's looking at the directory not the application.war on disc.

**Comment by Mark-J-Lawrence** [comment]
Closing as we will fix this internally
